---
title: "Combinations for different matrices"
output: html_notebook
---

```{r}
library(utils)
library(ggplot2)
```

```{r}
#epsilon = 1

diff_1 <- function(k) {
  c <- c()
  for (i in 1:k) {
    c[i] <- choose(k, i)
  }
  return(c)
}

col <- c()
j <- 1
n_1 <- function(end) {
  repeat {
    col[j] <- sum(diff_1(j))
    j <- j + 1
    if (j - 1 == end) {
      break
    }
  }
  return(log2(col[2:end]))
}

```

```{r}
col_num <- n_1(1000)
array <- c(2:1000)
plot(array, col_num)
```

```{r}
#diff = 1

diff_1 <- function(k) {
  c <- c()
  for (i in 1:k) {
    c[i] <- choose(k, i)
  }
  return(c)
}

col <- c()
j <- 1
n_1 <- function(end) {
  repeat {
    col[j] <- sum(diff_1(j))
    j <- j + 1
    if (j - 1 == end) {
      break
    }
  }
  return(col[2:end])
}

col_num <- n_1(17)
array <- c(2:17)
plot(array, col_num)
```

```{r}
# diff = k
# functions for trivial boundaries for k

sum_comb <- function(n, epsilon) {
  comb <- c()
  for (k in 1:(epsilon + 1)) {
    comb[k] <- choose(n, k - 1)
  }
  return(sum(comb))
}

bound_1 <- function(epsilon, n) {
  for (i in 0:epsilon) {
    array <- c(1:5)
    plot(array, log2(sum_comb(n, epsilon)) * c(1, 1, 1, 1, 1), type = 'l', col = 'green')
    lines(array, log2(sum_comb(n, 2 * epsilon - 1)) * c(1, 1, 1, 1, 1), col = 'red')
  }
}
```

```{r}
# diff = k
# functions for trivial boundaries for k

sum_comb <- function(n, epsilon) {
  comb <- c()
  for (k in 1:(epsilon + 1)) {
    comb[k] <- choose(n, k - 1)
  }
  return(sum(comb))
}

bound_1 <- function(epsilon, n) {
  array  <- seq(1, 2, 3)
  for (i in 0:epsilon) {
    lower <- log2(sum_comb(n, epsilon)) * c(1, 1, 1)
    upper <- log2(sum_comb(n, 2 * epsilon - 1)) * c(1, 1, 1)
    bounds <- data.frame(array, lower, upper)
    ggplot(bounds, aes(array)) + 
      geom_line(aes(y = upper), colour = "red") + 
      geom_line(aes(y = lower), colour = "green")
  }
}
```

```{r}
tyu <- bound_1(3, 5667)
```

```{r}
array <- c(1, 2, 3)
lower <- log2(sum_comb(47, 8)) * c(1, 1, 1)
upper <- log2(sum_comb(47, 2 * 8 - 1)) * c(1, 1, 1)
bounds <- data.frame(array, lower, upper)
ggplot(bounds, aes(array)) + 
  geom_line(aes(y = upper), colour = "red") + 
  geom_line(aes(y = lower), colour = "green")
```

```{r}
array <- c(1, 2, 3)
lower <- log2(sum_comb(47, 30)) * c(1, 1, 1)
upper <- log2(sum_comb(47, 2 * 30 - 1)) * c(1, 1, 1)
bounds <- data.frame(array, lower, upper)
ggplot(bounds, aes(array)) + 
  geom_line(aes(y = upper), colour = "red") + 
  geom_line(aes(y = lower), colour = "green")
```










